/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Tagged-PDF and accessibility signals. */
export interface AccessibilityInfo {
  /** Catalog language value when present. */
  language?: string
  /** `/MarkInfo /Marked` value when present. */
  markInfoMarked?: boolean
  /** Structure tree root exposes a role map. */
  hasRoleMap: boolean
  /** Number of structure roles reached before the traversal budget. */
  structureRoleCount: number
  /** Structure traversal stopped because the item budget was reached. */
  truncated: boolean
}

/** Document information dictionary fields. */
export interface DocumentInfoInfo {
  /** `/Title`. */
  title?: string
  /** `/Author`. */
  author?: string
  /** `/Subject`. */
  subject?: string
  /** `/Keywords`. */
  keywords?: string
  /** `/Creator`. */
  creator?: string
  /** `/Producer`. */
  producer?: string
  /** `/CreationDate`. */
  creationDate?: string
  /** `/ModDate`. */
  modificationDate?: string
}

/** Non-rendering catalog and structure signals. */
export interface DocumentStructureInfo {
  /** Catalog contains XMP metadata. */
  hasXmpMetadata: boolean
  /** Catalog contains `/MarkInfo`. */
  hasMarkInfo: boolean
  /** Catalog contains `/StructTreeRoot`. */
  hasStructTreeRoot: boolean
  /** Catalog names expose embedded files. */
  hasEmbeddedFiles: boolean
  /** Catalog declares a portfolio collection. */
  hasPortfolioCollection: boolean
  /** Document exposes at least one AcroForm signature field. */
  hasSignatureFields: boolean
}

/** Inspects document metadata on the Node-API worker pool. */
export declare function inspect(input: Buffer): Promise<InspectedDocument>

/** Metadata returned by [`inspect`]. */
export interface InspectedDocument {
  /** Number of pages resolved by the native parser. */
  pageCount: number
  /** First page size when available. */
  firstPage?: PageSizeInfo
  /** Document information dictionary fields. */
  info: DocumentInfoInfo
  /** Non-rendering catalog and structure signals. */
  structure: DocumentStructureInfo
  /** Tagged-PDF and accessibility-related signals. */
  accessibility: AccessibilityInfo
  /** Optional content group and layer-state signals. */
  optionalContent: OptionalContentInfo
}

/** Optional content group and layer-state signals. */
export interface OptionalContentInfo {
  /** Catalog contains `/OCProperties`. */
  hasOcProperties: boolean
  /** Number of optional content groups listed in `/OCProperties /OCGs`. */
  groupCount: number
  /** Default optional-content base state. */
  baseState: string
  /** Metadata found behavior native rendering does not implement interactively. */
  hasUnsupportedBehavior: boolean
}

/** PDF page size in user-space units. */
export interface PageSizeInfo {
  /** Page width. */
  width: number
  /** Page height. */
  height: number
}

/** Renders one PDF page on the Node-API worker pool. */
export declare function render(input: Buffer, options?: RenderOptions | undefined | null): Promise<RenderedThumbnail>

/** Thumbnail returned by [`render`]. */
export interface RenderedThumbnail {
  /** Output width in pixels. */
  width: number
  /** Output height in pixels. */
  height: number
  /** Number of bytes between adjacent raw RGBA rows, or `0` for encoded PNG. */
  stride: number
  /** Byte payload format, currently `rgba8` or `png`. */
  pixelFormat: string
  /** Requested output format, currently `rgba` or `png`. */
  outputFormat: string
  /** Thumbnail bytes as a Node.js `Buffer`. */
  data: Buffer
}

/** Options accepted by [`render`]. */
export interface RenderOptions {
  /** Zero-based page index. Defaults to `0`. */
  pageIndex?: number
  /** Maximum output width or height in pixels. Defaults to the Rust facade default. */
  maxEdge?: number
  /** RGBA background used for transparent pages. Defaults to opaque white. */
  background?: RgbaOptions
  /** Output encoding. Supported values are `rgba` and `png`. */
  outputFormat?: string
  /** Per-render timeout in milliseconds. */
  timeoutMs?: number
  /** Annotation visibility mode. Supported values are `screen` and `print`. */
  annotationMode?: string
  /**
   * AcroForm appearance handling. Supported values are `document-state` and
   * `requested-mutation`.
   */
  formAppearanceMode?: string
}

/** RGBA background channels. */
export interface RgbaOptions {
  /** Red channel. */
  r: number
  /** Green channel. */
  g: number
  /** Blue channel. */
  b: number
  /** Alpha channel. */
  a: number
}
