#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

node --input-type=module <<'NODE'
import fs from "node:fs";

const manifestPath = "fixtures/cross-producer-fusion-manifest.tsv";
const matrixPath = "fixtures/cross-producer-fusion-matrix.tsv";

function readTsv(path, expectedColumns) {
  const lines = fs.readFileSync(path, "utf8").trimEnd().split("\n");
  const header = lines[0].split("\t");
  if (header.length !== expectedColumns) {
    throw new Error(`${path} header has ${header.length} columns, expected ${expectedColumns}`);
  }
  return lines.slice(1).map((line, index) => {
    const columns = line.split("\t");
    if (columns.length !== expectedColumns) {
      throw new Error(`${path}:${index + 2} has ${columns.length} columns, expected ${expectedColumns}`);
    }
    return Object.fromEntries(header.map((name, columnIndex) => [name, columns[columnIndex]]));
  });
}

const manifest = readTsv(manifestPath, 7);
const matrix = readTsv(matrixPath, 12);
const manifestByPath = new Map(manifest.map((row) => [row.path, row]));
const producersByWorkflow = new Map();
const producersByFamily = new Map();

for (const row of manifest) {
  if (!fs.existsSync(row.path)) {
    throw new Error(`${row.path} does not exist`);
  }
  if (row.source !== "scripts/generate_fixtures.py") {
    throw new Error(`${row.path} must be generated by scripts/generate_fixtures.py`);
  }
  if (row.license !== "MIT OR Apache-2.0") {
    throw new Error(`${row.path} must use the generated fixture license`);
  }
  const features = row.features.split(",");
  const producer = features.find((feature) => feature.startsWith("producer:"));
  const workflow = features.find((feature) => feature.startsWith("workflow:"));
  const expected = features.find((feature) => feature.startsWith("expected:"));
  if (!producer || !workflow || !expected) {
    throw new Error(`${row.path} must include producer, workflow, and expected tags`);
  }
  if (features.some((feature) => feature === "privacy:private" || feature === "privacy:local-only")) {
    throw new Error(`${row.path} must not include private/local-only privacy tags`);
  }
  const workflowKey = workflow.slice("workflow:".length);
  const producerKey = producer.slice("producer:".length);
  if (!producersByWorkflow.has(workflowKey)) {
    producersByWorkflow.set(workflowKey, new Set());
  }
  producersByWorkflow.get(workflowKey).add(producerKey);
  if (!producersByFamily.has(row.family)) {
    producersByFamily.set(row.family, new Set());
  }
  producersByFamily.get(row.family).add(producerKey);
}

for (const [workflow, producers] of producersByWorkflow) {
  if (producers.size < 2) {
    throw new Error(`${workflow} must cover at least two producers`);
  }
}

for (const [family, producers] of producersByFamily) {
  if (producers.size < 2) {
    throw new Error(`${family} must cover at least two producers`);
  }
}

for (const row of matrix) {
  if (!manifestByPath.has(row.path)) {
    throw new Error(`${row.path} appears in matrix but not manifest`);
  }
  const manifestRow = manifestByPath.get(row.path);
  if (manifestRow.family !== row.document_family) {
    throw new Error(`${row.path} family mismatch between manifest and matrix`);
  }
  if (row.current_status === "supported" && row.typed_cause !== "none") {
    throw new Error(`${row.path} supported rows must use typed_cause=none`);
  }
  if (row.current_status !== "supported" && row.owner_route === "none") {
    throw new Error(`${row.path} non-supported rows need an owner route`);
  }
  if (!row.minimization_notes.startsWith("Generated")) {
    throw new Error(`${row.path} must document generated minimization`);
  }
}

console.log(
  `${manifest.length} fusion manifest rows, ${matrix.length} matrix rows, ${producersByWorkflow.size} workflows validated`,
);
NODE
